### PR TITLE
styles

### PR DESCRIPTION
**Pull request by marchwiany**
### Items Addressed
- Styles

### Out of scope
- [ ] n/a

### QA Login
Credentials: { email } // { password } - { user type }

### QA Steps
- [ ] n/a

### Code Review Questions
- Something you want to highlight to the code reviewer (if none, put "general review")

## Author Checklist
- [ ] Assign a dev reviewer when you're ready for code review
- [ ] Assign a product reviewer when you're ready for QA

### CODE REVIEW

**Comment by chawes13** [comment]
@marchwiany This is amazing! I made a few small updates to make most areas of the expanded contact clickable. Take a look and see if there's anything that you would do differently.

Lastly, would you be able to swap out the lpl-192 and lpl-512 pngs with a white background behind the logo you made and replace "Made with <3 by LaunchPadLab" with "The Village People"? With that finishing touch, I think this will be ready for production. Thank you so much!!!

**Comment by chawes13** [comment]
@marchwiany I did a little browser stack testing this morning and found a few things:
- Contact cards on iOS Safari have a white trim on the top and bottom of the button displaying contact name (https://share.getcloudapp.com/2NuXQjRz)
- Top of page bounces / flashes on iOS Safari and Android Chrome when scrolling down to refresh ([iOS](https://share.getcloudapp.com/GGukbRey) & [android](https://share.getcloudapp.com/qGud4NWm))
  - I'm not sure if this is a BrowserStack thing as I haven't tested this on a physical phone yet?

**Comment by marchwiany** [comment]
@chawes13 fixed the safari border issue and updated the logo image! And as far has the scroll down piece that you noticed, I believe that's just a browserstack thing.

**Comment by chawes13** [comment]
Thanks @marchwiany!

**Pull request merged**
